movie_go/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from movie_go.views import basic, products, basket, orders, dashboard
app_name = 'movie_go'
urlpatterns = [
    path('', views.basic.index, name='index'),
    path('about/',views.basic.about, name='about'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('movies/', views.basic.movies, name='movies'),
    path('movies/<str:genre>', views.basic.movies, name='movies'),
    path('movie_details/<int:id>', views.basic.movie_details, name='movie_details'),
    path('zone_detail/<int:movie_id>', views.basic.zone_detail, name= 'zone_detail'),
    path('basket_add/<int:product_id>/', views.basket.basket_add, name ='basket_add'),
    path('basket_remove/<int:product_id>/', views.basket.basket_remove, name ='basket_remove'),
    path('basket_detail/', views.basket.basket_detail, name ='basket_detail'),
    path('product_list/', views.products.product_list, name='product_list'),
    path('product/<int:id>/', views.products.product_detail, name='product_detail'),
    path('product_new/<int:movie_id>/<int:zone_id>', views.products.product_new, name= 'product_new'),
    path('product_new/', views.products.product_new, name= 'product_new'),
    path('product/<int:id>/edit/', views.products.product_edit, name= 'product_edit'),
    path('product/<int:id>/delete/', views.products.product_delete, name= 'product_delete'),
    path('purchase/', views.basic.purchase, name ='purchase'),
    path('payment/', views.basic.payment, name ='payment'),
    path('signup/', views.basic.signup, name='signup'),
    path('user_order_list/', views.orders.user_order_list, name='user_order_list'),
    path('user_order/<int:id>/', views.orders.user_order_detail, name= 'user_order_detail'),
    path('dashboard/', views.dashboard.dashboard, name='dashboard'),
    path('success/<int:id>', views.basic.success, name='success'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_go.urls',  namespace='movie_go')),
]

#handling the 404 error, calling the corresponding view function incase of error.
handler404 = 'movie_go.views.basic.error_404_view'
#handling the 500 error, calling the corresponding view function incase of error.
handler500 = 'movie_go.views.basic.error_500_view'
#handling the 403 error, calling the corresponding view function incase of error.
handler403 = 'movie_go.views.basic.error_403_view'

movie_go/views/basic.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from movie_go.models import Zones, Movies, Customer, Order, Product, Cart, LineItem
from movie_go.forms import SignUpForm
from movie_go.views.basket import Basket
import ast

genres = ['Animation', 'Comedy', 'Family', 'Adventure', 'Horror','Crime','Thriller','Drama','Fantasy']
movie_all = Movies.objects.all()
movie_names = [movie.title for movie in movie_all]

#helper functions
#get from models.
def get_from_model(Model,id):
    obj = Model.objects.get(id=id)
    return obj

# Create your views here.
#view for new customer signup.
def signup(request):
    try:
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            #using the data fetched from the form to create user account
            user.customer.first_name = form.cleaned_data.get('first_name')
            user.customer.last_name = form.cleaned_data.get('last_name')
            user.customer.address = form.cleaned_data.get('address')
            user.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            #using the in-built authentication method for authenticating the new user
            user = authenticate(username=username, password= password)
            #logging in the new user
            login(request, user)
            return redirect('/')
        return render(request, 'signup.html', {'form': form})
    except:
        return render(request, 'movie_go/500.html')
# index page view
#homepage that contains all the basic information about the application.
def index(request):
    try:
        zones = Zones.objects.all()
        movies = movie_all.filter(votes__vote_average__gte=8).order_by('votes__vote_average')[:3]
        return render(request, 'movie_go/index.html', {'zones': zones, 'movies': movies})
    except:
        return render(request, 'movie_go/500.html')
#about page that contains a detailed overview of the application.
def about(request):
    try:
        return render(request, 'movie_go/about.html')
    except:
        return render(request, 'movie_go/500.html')

#the movies page that lets user search and view general information about movies.
def movies(request,genre = None):
    try:
        no_movies = None
        #displaying top-rated movies first
        movies = movie_all.filter(votes__vote_average__gte=8).order_by('votes__vote_average')[:12]
        if request.method == 'POST':
            #getting the searched movie name from user
            movie_name = request.POST.get('movie').strip()
            if movie_name != '':
                #fetching the movie searched by the user
                movies = movie_all.filter(title=movie_name)
                if not movies:
                    #incase no movie was found, convey the same to the user
                    no_movies = f'No results for {movie_name}. Try checking the spelling'
        #if the user clicks on a genre, display movies accordingly
        if genre:
            movies = movie_all.filter(genres__contains=genre)
        return render(request, 'movie_go/movies.html', {'movies': movies, 'movie_names': movie_names,'genres': genres, 'no_movies': no_movies})
    except:
        return render(request, 'movie_go/500.html')

#displays in-detail information about the movie selected by the user from the movies page.
def movie_details(request,id):
    try:
        movie = get_from_model(Movies,id)
        companies = eval(str(movie.production_companies))
        languages = eval(str(movie.spoken_languages))
        language_list = [language['name'] for language in languages]
        companies_list = [company['name'] for company in companies]
        return render(request, 'movie_go/movie_details.html',{'movie': movie, 'companies':', '.join(companies_list), 'languages': ', '.join(language_list)})
    except:
        return render(request, 'movie_go/500.html')

#displays in-detail information about all the zones present for the user to select.
def zone_detail(request, movie_id):
    try:
        movie = get_from_model(Movies,movie_id)
        zones = Zones.objects.all()
        return render(request, 'movie_go/zone_detail.html',{'movie':movie,'zones': zones})
    except:
        return render(request, 'movie_go/500.html')


#allows the user to check and purchase the contents of his/her basket.
@login_required(login_url='movie_go:login')
def purchase(request):
    try:
        user = request.user
        basket = Basket(request)
        return render(request, 'movie_go/purchase.html', {'basket': basket, 'user': user})
    except:
        return render(request, 'movie_go/500.html')

# allows user to create an order and delete the basket session.
def payment(request):
    try:
        basket = Basket(request)
        user = request.user
        customer = get_object_or_404(Customer, user_id=user.id)
        order = Order.objects.create(customer=customer)
        order.refresh_from_db()
        for item in basket:
            product_item = get_object_or_404(Product, id=item['product_id'])
            cart = Cart.objects.create(product = product_item, quantity=item['quantity'])
            cart.refresh_from_db()
            line_item = LineItem.objects.create(quantity=item['quantity'], product=product_item, cart=cart,  order = order)
        basket.clear()
        request.session['deleted'] = 'thanks for your purchase'
        return redirect('movie_go:success', id=order.id )
    except:
        return render(request, 'movie_go/500.html')

#displays order success information to the user
def success(request,id):
    try:
        order = Order.objects.get(id=id)
        lineitems = LineItem.objects.filter(order=order)
        return render(request, 'movie_go/success.html', {'order': order, 'lineitems': lineitems})
    except:
        return render(request, 'movie_go/500.html')

#function that gets called incase of a 404 page not found error.
def error_404_view(request, exception):
    return render(request, 'movie_go/404.html', status=404)
#function that gets called incase of a 500 internal server error.
def error_500_view(request):
    return render(request, 'movie_go/500.html', status=500)
#function that gets called incase of a 403 forbidden error.
def error_403_view(request, exception):
    return render(request, 'movie_go/403.html', status=403)

movie_go/views/basket.py
from decimal import Decimal
from django.conf import settings
from django.shortcuts import redirect, render, get_object_or_404
from django.views.decorators.http import require_POST
from movie_go.models import Product
from movie_go.forms import BasketAddProductForm 

#creating a Basket class and a few methods to manipulate the basket
class Basket(object):
    # a data transfer object to shift items from cart to page
    # inspired by Django 3 by Example (2020) by Antonio Mele
    # https://github.com/PacktPublishing/Django-3-by-Example/
    
    #creating an initial version of a basket
    def __init__(self, request):
        self.session = request.session
        basket = self.session.get(settings.BASKET_SESSION_ID)
        if not basket:
            # save an empty basket in the session
            basket = self.session[settings.BASKET_SESSION_ID] = {}
        self.basket = basket
    #to iterate over the items in the basket and fetch the corresponding product from database.
    def __iter__(self):
        product_ids = self.basket.keys()
        # get the product objects and add them to the basket
        products = Product.objects.filter(id__in=product_ids)

        basket = self.basket.copy()
        for product in products:
            basket[str(product.id)]['product'] = product
            basket[str(product.id)]['product_id'] = product.id

        for item in basket.values():
            item['price'] = Decimal(item['price'])
            item['total_price'] = item['price'] * item['quantity']
            yield item

    #to return the number of items in the basket.
    def __len__(self):
        return sum(item['quantity'] for item in self.basket.values())
    #Add a product to the basket or update its quantity.
    def add(self, product, quantity=1, override_quantity=False):
        product_id = str(product.id)
        if product_id not in self.basket:
            self.basket[product_id] = {'quantity': 0,
                                      'price': str(product.price)}
        if override_quantity:
            self.basket[product_id]['quantity'] = quantity
        else:
            self.basket[product_id]['quantity'] += quantity
        self.save()

    # mark the session as "modified" to make sure it gets saved
    def save(self):
        self.session.modified = True

    #to remove a particular product from basket
    def remove(self, product):
        """
        Remove a product from the basket.
        """
        product_id = str(product.id)
        if product_id in self.basket:
            del self.basket[product_id]
            self.save()
    #to clear the basket session
    def clear(self):
        # remove basket from session
        del self.session[settings.BASKET_SESSION_ID]
        self.save()
    #to get the total price from the basket contents
    def get_total_price(self):
        return sum(Decimal(item['price']) * item['quantity'] for item in self.basket.values())

#allows user to add products to the basket, and view the contents in the basket once the 
#product has been added.
@require_POST
def basket_add(request, product_id):
    try:
        basket = Basket(request)
        product = get_object_or_404(Product, id=product_id)
        form = BasketAddProductForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            basket.add(product=product,quantity=cd['quantity'],override_quantity=cd['override'])
        return redirect('movie_go:basket_detail')
    except:
        return render(request, 'movie_go/500.html')

#allows user to remove products from the basket, and view the contents in the basket once the 
#product has been removed.
@require_POST
def basket_remove(request, product_id):
    try:
        if product_id != 0:
            basket = Basket(request)
            product = get_object_or_404(Product, id=product_id)
            basket.remove(product)
            return redirect('movie_go:basket_detail')
        else:
            return redirect('movie_go:movies')
    except:
        return render(request, 'movie_go/500.html')

#allows the user to veiw contents of the basket.
def basket_detail(request):
    try:
        basket = Basket(request)
        for item in basket:
            item['update_quantity_form'] = BasketAddProductForm(initial={'quantity': item['quantity'],'override': True})
        return render(request, 'movie_go/basket.html', {'basket': basket})
    except:
        return render(request, 'movie_go/500.html')

movie_go/views/dashboard.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from movie_go.models import Zones, Movies, Customer, Order, Product, Cart, LineItem
from datetime import datetime
from collections import Counter
from django.core.exceptions import PermissionDenied
#Helper functions
#function to return the count of the model instances each date
def chart_data(Model):
    op = []
    total_data = Model.objects.values_list('created_date').order_by('-created_date')
    for date in total_data:
        op.append(str(date[0])[:10])
    return dict(Counter(op))

#function to return the count of the total model instances
def data_count(Model):
    data = Model.objects.count()
    return data


#function to return the count of the instances created today.
def data_today(Model):
    current = str(datetime.now())[:10]
    data = Model.objects.filter(created_date__contains=current).count()
    return data

#function that processes the data in order to be sent to the chart.js
@login_required
def dashboard(request):
    user = request.user
    if user.is_authenticated & user.is_staff:
        #chart processsing
        order_data = chart_data(Order)
        x1Values = order_data.keys()
        y1Values = order_data.values()
        listx1 = list(x1Values)
        listx1.reverse()
        listy1 = list(y1Values)
        listy1.reverse()
        customer_data = chart_data(Customer)
        x2Values = customer_data.keys()
        y2Values = customer_data.values()
        listx2 = list(x2Values)
        listx2.reverse()
        listy2 = list(y2Values)
        listy2.reverse()
        #count the number of orders and customers each date.
        order_count = data_count(Order)
        customers_count = data_count(Customer)
        #count the number of orders and customers today.
        orders_today = data_today(Order)
        customers_today = data_today(Customer)
        return render(request, 'movie_go/dashboard.html',{'x1Values': listx1,'y1Values': listy1,'x2Values': listx2,'y2Values': listy2, 'order_count': order_count, 'customers_count': customers_count, 'orders_today': orders_today, 'customers_today': customers_today})
    elif not user.is_staff & user.is_authenticated:
        raise PermissionDenied()
    else:
        return redirect('movie_go:login')

movie_go/views/orders.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from movie_go.models import LineItem, Order, Customer
from django.contrib.auth.decorators import login_required

#allows the users to view teh list of orders they have made.
@login_required(login_url='movie_go:login')
def user_order_list(request):
    try:
        user = request.user
        customer = get_object_or_404(Customer, user_id=user.id)
        orders = Order.objects.filter(customer=customer)
        return render(request, 'movie_go/order_list.html', {'orders': orders, 'user': user})
    except:
        return render(request, 'movie_go/500.html')

#allows the user to view the details of a particular order.
@login_required(login_url='movie_go:login')
def user_order_detail(request, id):
    try:
        order = get_object_or_404(Order, id=id)
        customer = order.customer
        user = get_object_or_404(User, id=customer.pk)
        line_items = LineItem.objects.filter(order_id=order.id)
        return render(request, 'movie_go/order_detail.html', {'order' : order, 'user': user, 'line_items': line_items})
    except:
        return render(request, 'movie_go/500.html')

movie_go/templates/movie_go/about.html
{% extends "movie_go/base.html" %}
{% load static %}
{% block content %}
<div class="about">
    <p>This website has been built as a part of a student assignment. The dataset for the movies has been taken from 
        <a href="https://www.kaggle.com/datasets/rounakbanik/the-movies-dataset?select=movies_metadata.csv">Kaggle</a>
        The images for all the movies have been taken from the <a href="https://www.themoviedb.org/documentation/api">TMDB API </a>
    </p>
    <p>This website was built using Django, which is an open-source framework for building web based applications in Python. <br>
    Here are some of the features of this application.</p>
    <ul>
        <li>
            1. A movies page that lists out the top-rated movies and allows users to search for a movie based on name and genre.
        </li>
        <li>
            2. A zone details page that lists the zones available to watch the selected movie.
        </li>
        <li>
            3. An extensive authentication system that allows the users to signup, login and logout securely.
        </li>
        <li>
            4. A dashboard for staff users to monitor the orders and customers count everyday.
        </li>
        <li>
            5. An orders page for the customers to view the orders they have made.
        </li>
    </ul>
    <p>Built by: Abinaya Elangovan</p>
    
</div>
{% endblock%}

movie_go/templates/movie_go/basket.html
{% extends 'movie_go/base.html' %}
{% block content %}
<div class="info">
<h2>You have these in your basket:</h2>
 <table>
  {% for item in basket %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{% url 'movie_go:product_detail' id=product.id|add:'0' %}">product
              </a>
            </td>
            <td>
              <form action="{% url 'movie_go:basket_add' product.id|add:'0' %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Update" name="update" class="basket-btn">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url 'movie_go:basket_remove' product.id|add:'0' %}" method="post">
                <input type="submit" value="Remove" name="remove" class="basket-btn">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">{{ item.price }} GBP * {{item.quantity}}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      {% if basket.get_total_price != 0 %}
      <tr class="total">
        <td>Total</td>
        <td colspan="2"></td>
        <td class="num">{{ basket.get_total_price }} GBP</td>
      </tr>
      {% endif %}
  </table>
  <p class="text-right">
    {% if basket.get_total_price != 0 %}
    <a href="{% url 'movie_go:purchase' %}" class="purchase_btn">Purchase</a> <br>
    {% else %}
    <p>Cart is empty</p>
    {%endif%}
    <a href="{% url 'movie_go:movies' %}" class="button
    light">Continue shopping</a>
  </p>
</div>  
 {% endblock %}

movie_go/templates/movie_go/index.html
{% extends "movie_go/base.html" %}
{% load static %}
{%block style%}
<style>

</style>
{%endblock%}
{% block content %}
{% if user.is_authenticated %}
    <p class="welcome">Welcome back, {{ user.first_name }} 🥳</p>
{%endif%}
<section class="index">
    <div class="banner">
        <img src="https://image.tmdb.org/t/p/w500/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg">
        <div class="banner-text">
            <h2>For a fantastic movie-watching experience</h2>
            <p> Watch all the latest top-rated movies with your friends in a threatre-like environment</p>
            <p> With resolution ranging up to 4K </p>
            <a class="btn" href="{% url 'movie_go:movies'%}">Explore</a>
        </div>
        
    </div>
    <h2 class="zones-heading">Select zones to watch !!!</h2>
    <div class="zones">
        {%for zone in zones%}
            <div class="zone-items">
                <img src = "{% static 'images/' %}{{zone.image}}">
                <h4>{{zone.seats}} seats</h4>
                <p>{{zone.resolution}} resolution</p>
            </div>
        {%endfor%}
    </div>
    <h2 class="zones-heading">Select movies to watch !!!</h2>
    <a class="index-a" href="{% url 'movie_go:movies'%}">view more &rAarr;</a>
    <div class="movies">
        {%for movie in movies%}
            <div class="movie-items">
                <a href="{% url 'movie_go:movie_details' movie.id %}"><img src = "https://image.tmdb.org/t/p/w500{{movie.poster_path}}" alt="image not found"></a>
                <h4>{{movie.title}}, vote: {{movie.votes.vote_average}}</h4>
                <p>{{movie.release_date}}</p>
            </div>
        {%endfor%}
    </div>
</section>
<p class="credit">All the movie images are from : 'https://www.themoviedb.org/'</p>
{%endblock%}

movie_go/templates/movie_go/movie_details.html
{% extends 'movie_go/base.html' %}
{% load static %}
{% block content %}
<h1 class="details-heading">{{movie.title}}</h1>
    <div class="details">
        <div class="product-image">
            <img src="https://image.tmdb.org/t/p/w500{{movie.poster_path}}" alt="image not found">
        </div>
        <div class="product-details">
            <h3>{{movie.tagline}}</h3>
            <h4>Available in: {{languages}}</h4>
            <p id="overview">{{movie.overview}}</p>
            <h5>vote {{movie.votes}}</h5>
            <p>produced by: {{companies}}</p>
            <p>duration: {{movie.runtime}} minutes</p>
            <p>revenue: {{movie.revenue}} USD</p>
            <h4>Price: 7 GBP</h4>
            <a href="{% url 'movie_go:zone_detail' movie.id%}" class="btn">Add to cart 🛒</a>
        </div>
    </div>
    <p class="credit">All the movie images are from : 'https://www.themoviedb.org/'</p>
{%endblock%}

movie_go/templates/movie_go/movies.html
{% extends "movie_go/base.html" %}
{% load static %}
{% block content %}
    <section class="movies-section">
        <form class="form" action="{%url 'movie_go:movies'%}" method="POST">
            {% csrf_token %}
            <label for="movie">Search for a movie: </label>
            <input list="movie-names" id="movie" name="movie">
            <datalist id="movie-names">
                {% for movie in movie_names%}
                <option value="{{movie}}">
                {%endfor%}
            </datalist>
            <input type="submit" name="submit" value="search" class="search">
        </form>
        <div class="genre-list">
            {%for genre in genres%}
                <a href="{% url 'movie_go:movies' genre %}" class="genre-a">{{genre}}</a>
            {%endfor%}
        </div>
        {% if no_movies %}
            <p>{{no_movies}}</p>
        {% else %}
        <div class="moviesgrid">
            {%for movie in movies%}
            <div class="movieg-items">
                <a href="{% url 'movie_go:movie_details' movie.id %}"><img src = "https://image.tmdb.org/t/p/w500{{movie.poster_path}}" alt="image not found"></a>
                <h4>{{movie.title}}, vote: {{movie.votes.vote_average}}</h4>
                <p>{{movie.release_date}}</p>
            </div>
            {%endfor%}
        </div>
        {% endif %}
    </section>
    <p class="credit">All the movie images are from : 'https://www.themoviedb.org/'</p>
{%endblock%}

movie_go/templates/movie_go/order_detail.html
{% extends 'movie_go/base.html' %}
{% block content %}
<div class="info">
    <div class="info">
    <h1>Order details</h1>
    <p>
 The order was placed on: {{ order.created_date }} 
   </p>
  <p>The order includes these items:</p>
  {% for line_item in line_items %}
  <h4>{{line_item.id}}</h4>
  <p>
   Quantity: {{ line_item.quantity}}
  </p> <br>
  <p>You're watching {{ line_item.product.movie.title}} at {{ line_item.product.zone.address}}</p> <br>
  <p>Date and Time: {{line_item.product.booking_date}}, {{line_item.product.booking_time}}</p>
  
  {% endfor %}
</div>
   </div>
    {% endblock %}

movie_go/templates/movie_go/order_list.html
  {% extends 'movie_go/base.html' %}
  {% block content %}
  <div class="info">
    <h1>Order List for {{user.first_name}} ✨</h1>
    
    {% for order in orders %}
    <p>This is order <b> <a href="{% url 'movie_go:user_order_detail' id=order.id %}">{{order.id }}</a></b> for
       {{order.customer.id}}. The order was placed on: {{ order.created_date }} 
    </p>
    {% endfor %}
</div>
    {% endblock %}

movie_go/templates/movie_go/product_detail.html
{% extends 'movie_go/base.html' %}
{% block content %}
<div class="info">
    <h1>Product Details</h1>
    {% if product %}
    <p>Product {{ product.id }}: <a href="{% url 'movie_go:product_edit' id=product.id %}">Edit</a>
      This is product {{ product.id }} which costs
      {{product.price}} GBP. The product was added on: {{ product.created_date }} 
   </p> <br>
   <p>Movie: {{product.movie.title}} </p>
   <p>Zone: {{product.zone.address}}</p>
   <p>Booking date: {{product.booking_date}}</p>
   <p>Booking time: {{product.booking_time}}</p>
   <p>
    <form action="{% url 'movie_go:basket_add' product.id %}" method="post">
      {{ basket_product_form }}
      {% csrf_token %}
      <input type="submit" name="submit" value="Add to Basket 🛒" class="basket-btn">
    </form>
       </p>
   <p><a href="{% url 'movie_go:product_delete' id=product.id %}">Delete the product</a></p>
   {% else %}
   <p>No product added.
       <a href="{% url 'movie_go:movies' %}" class="button
    light">Continue shopping</a></p>
   {% endif %}
</div>
    {% endblock %}

movie_go/templates/movie_go/product_edit.html
{% extends 'movie_go/base.html' %}
{% block content %}
<div class="info">
    <h1>Product confirmation</h1> <br>

    <form method="POST" class="product_form">
        {% csrf_token %}
      {{ form.as_p}} <br>
      <button type="submit" name="submit" class="basket-btn">Save</button>
    </form>
</div>
    {% endblock %}

movie_go/templates/movie_go/product_list.html
  {% extends 'movie_go/base.html' %}
  {% block content %}
<div class="info">
    <h1>Product List</h1>
<p>{{ deleted }} </p>
    <p><a href="{% url 'movie_go:product_new' %}">Add a new product</a></p>
    {% for product in products %}
    <p><b> <a href="{% url 'movie_go:product_detail' id=product.id %}">{{product.id}}</a></b>
      This is product {{ product.id }} which costs
       {{product.price}}. The product was added on: {{ product.created_date }} 
{% endfor %}
</div>
{% endblock %}

movie_go/templates/movie_go/purchase.html
{% extends 'movie_go/base.html' %}
{% block content %}
<div class="info">
<h2>You have these in your basket:</h2>
  {% for item in basket %}
    {% with product=item.product %}
 
<p>Price per item {{ item.price }} GBP * {{item.quantity}}</p> <br>
<p>Total Price: {{ item.total_price }} GBP</p>
     {% endwith %}
   {% endfor %} <br>
   <p>
    <form action="/payment/" method="post">
       {% csrf_token %}
       <p>Please enter your credit card details</p> <br>
       <input type='text' name='first_name' value="{{user.first_name}}" disabled>
       <input type='text' name='last_name' value="{{user.last_name}}" disabled>     <br>
       <label for='payment'>Card Type:</label><input type='text' size=5 name='payment' required>
       <input type="number" name="total" value="Total Payment:" required minlength="12">
       <input type="submit" value="Payment" name="submit" class="basket-btn">
       </form>
       </p>

</div>
 {% endblock %}

movie_go/templates/movie_go/success.html
  {% extends 'movie_go/base.html' %}
  {% block content %}
<div class="info">
    <h1>Congratulations! Your order has been placed</h1>
    <h3>Order details</h3>
    <p>
 The order was placed on: {{ order.created_date }} 
   </p>
  <p>The order includes these items:</p>
  {% for lineitem in lineitems %}
  <h4>{{lineitem.id}}</h4>
  <p>
   Quantity: {{ lineitem.quantity}}
  </p> <br>
  <p>You're watching {{ lineitem.product.movie.title}}</p> <br>
  <p>Date and Time: {{lineitem.product.booking_date}}, {{lineitem.product.booking_time}}</p> <br>
  <p>Venue: {{ lineitem.product.zone.address}}</p>
  
  {% endfor %}
</div>
{% endblock %}

movie_go/templates/movie_go/zone_detail.html
{% extends "movie_go/base.html" %}
{% load static %}
{% block content %}
    <section class="zones-section">
        <h2> Select a zone to watch {{movie.title}} </h2>
        <div class="zonesgrid">
            {%for zone in zones%}
            <div class="zonesg-items">
                <img src = "{% static 'images/' %}{{zone.image}}" alt="image not found">
                <h4>Number of seats: {{zone.seats}}</h4>
                <p>Screen Width: {{Zone.screenwidth}}</p>
                <p>Resolution: {{zone.resolution}}</p>
                <p>Location: {{zone.address}}</p>
                <p>Cost: {{zone.cost}} GBP</p>
                <a href="{% url 'movie_go:product_new' movie_id=movie.id zone_id=zone.id%}" class="btn-zone">Add to cart 🛒</a>
            </div>
            {%endfor%}
        </div>
    </section>
{%endblock%}